version: '3.7'

networks:
  test:
    name: fabric_test

services:
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.4.2
    restart: always
    labels:
      service: hyperledger-fabric
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
      - COUCHDB_HTTP_RANGE=false
    ports:
      - "5984:5984"
    volumes:
      - couchdb0-data:/opt/couchdb/data
    networks:
      - test

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0
    volumes:
      - org1-peer0-ledger:/var/hyperledger/production
    networks:
      - test

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0
    volumes:
      - org1-peer1-ledger:/var/hyperledger/production
    networks:
      - test




volumes:
  couchdb0-data:
  org1-peer0-ledger:
  org1-peer1-ledger:




